language: python

python:
  - 3.6

env:
  - DJANGO<4.0


install:
  - pip install -r requirements.txt
  - pip install coverage coveralls

script:
  - coverage run manage.py test

notifications:
    email:
      - martyn.clement@gmail.com

after_success:
  - coveralls
