# You can use a Docker image from Docker Hub or your own container registry
image: python:2.7
   
pipelines:
  default:
    - step:
        script:
          - pip install -r requirements.txt
          - python manage.py migrate --noinput
          - python manage.py test

